spring:

  freemarker:
    expose-session-attributes: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_starter?createDatabaseIfNotExist=true
    username: root
    password: root
    max-active: 16
    max-idle: 4
    min-idle: 2
    initial-size: 2
    min-evictable-idle-time-millis: 1800000
    time-between-eviction-runs-millis: 1800000
    max-wait: 10000
    validation-query: SELECT 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
  jpa:
    generate-ddl: true

server:
  port: 8080
  address: 0.0.0.0
  session-timeout: 1800

security:
  user:
    name: admin
    password: admin
    role: ADMIN
  enable-csrf: false
  basic:
    enabled: true
    path: "/resource/**"
